# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-Assignment-Weather-Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-Assignment-Weather-Clone
  pod 'SwiftLint'  
  pod 'SnapKit'

end
