# 실행에서 제외할 룰 식별자
disabled_rules:
- line_length
- trailing_whitespace
- function_parameter_count
- file_length
- function_body_length
- nesting
# 린트 과정에서 무시할 파일 경로
excluded:
- Weather-App-Clone-Coding/Application/AppDelegate.swift
- Weather-App-Clone-Coding/Application/SceneDelegate.swift
- Weather-App-Clone-Coding/ExampleView.swift
- Weather-App-Clone-Coding/ExampleViewController.swift
- Weather-App-Clone-Coding/ExampleCollectionViewCell.swift
